name: deployment-fe

on:
  push:
    branches: main

  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"
      tags:
        description: "Test scenario tags"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Make static.js
        run: |
          cd ./src
          touch ./static.js
          echo "${{ secrets.STATIC }}" > ./static.js
        shell: bash

      - name: Build and push Docker image
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -f Dockerfile -t ${{ secrets.DOCKER_REPO }}:v0.1 .
          docker push ${{ secrets.DOCKER_REPO }}:v0.1

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.KEY }}
          script: |
            sudo docker pull ${{ secrets.DOCKER_REPO }}:v0.1
            sudo docker stop nginx-test-fe || true
            sudo docker rm nginx-test-fe || true
            sudo docker run --name nginx-test-fe -d -p 3000:3000 ${{ secrets.DOCKER_REPO }}:v0.1
            sudo docker image prune -f